server {
    listen 6080 default_server;
    listen [::]:6080 default_server;

    root /usr/share/novnc;
    index index.html vnc.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    # Low-Latency VNC WebSocket Bridge
    location /websockify {
        proxy_pass http://127.0.0.1:6081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # Real-Time PulseAudio Live Audio Stream
    location /audio.mp3 {
        proxy_pass http://127.0.0.1:5711/audio.mp3;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400s;
        proxy_set_header Connection "";
    }
}
